Update login.php
weixiong15/PHP_Basic_BookStore_Website pull request #2
Opened 2020-10-10 08:54 UTC by vikashviraj

2023-02-20 04:07 UTC, weixiong15 approved these changes

2024-07-27 10:41 UTC, Vignesh-Jothi requested changes
```php
<?php
if (isset($_GET['errcode'])) {
    $errorMessages = [
        1 => 'Invalid username or password. Please try again.',
        2 => 'Please login.'
    ];

    $errcode = intval($_GET['errcode']);
    if (array_key_exists($errcode, $errorMessages)) {
        echo '<span style="color: red;">' . htmlspecialchars($errorMessages[$errcode]) . '</span>';
    }
}
?>
```
This approach keeps the code clean, maintainable, and secure.

2024-07-29 01:37 UTC, ywxbear approved these changes

2024-07-29 01:42 UTC, ywxbear approved these changes

2024-07-29 01:42 UTC, ywxbear reviewed
Thanks for suggestion!

2024-12-30 18:58 UTC, closed without merging